In [2]:
import torch
import numpy as np
torch.__version__

'1.10.0+cu111'

In [5]:
arr_1 = np.array([1,2,3,4,5,6,7,8])
type(arr_1)

numpy.ndarray

#### Linked Tensor:

In [7]:
ts = torch.from_numpy(arr_1)
type(ts)

torch.Tensor

In [8]:
torch.as_tensor(arr_1)

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
arr_2d = np.arange(0.0, 20.0)
arr_2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [16]:
arr_2d = arr_2d.reshape(4, 5)
arr_2d

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.]])

In [17]:
ts_2 = torch.from_numpy(arr_2d)
ts_2

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]], dtype=torch.float64)

In [18]:
arr_1[0] = 67
print(arr_1)
print(ts)

[67  2  3  4  5  6  7  8]
tensor([67,  2,  3,  4,  5,  6,  7,  8])


#### Tensor not linked to numpy :

In [19]:
arr_3 = np.arange(1, 9)
arr_3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
ts_3 = torch.tensor(arr_3)
ts_3

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
arr_3[0] = 999
arr_3

array([999,   2,   3,   4,   5,   6,   7,   8])

In [22]:
ts_3

tensor([1, 2, 3, 4, 5, 6, 7, 8])

In [23]:
ts3 = torch.Tensor(arr_3)
ts3

tensor([999.,   2.,   3.,   4.,   5.,   6.,   7.,   8.])

In [24]:
# Allocate a memory/placeholder
torch.empty(3,3)

tensor([[-6.4802e+30,  3.0637e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  6.0000e+00],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22]])

In [27]:
torch.zeros(4, 4, dtype=torch.int64)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [28]:
torch.arange(0, 18, 2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [31]:
torch.linspace(0, 10, 18)

tensor([ 0.0000,  0.5882,  1.1765,  1.7647,  2.3529,  2.9412,  3.5294,  4.1176,
         4.7059,  5.2941,  5.8824,  6.4706,  7.0588,  7.6471,  8.2353,  8.8235,
         9.4118, 10.0000])

In [32]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [33]:
ts_2 = ts_2.type(torch.int64)
ts_2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

#### Random samples from uniform distribution :

In [34]:
torch.rand(5,6)

tensor([[0.7148, 0.5677, 0.1376, 0.2565, 0.9701, 0.4828],
        [0.9062, 0.8401, 0.9084, 0.6314, 0.3491, 0.3931],
        [0.7612, 0.2935, 0.4993, 0.5495, 0.3239, 0.5771],
        [0.3991, 0.8156, 0.8362, 0.7787, 0.6628, 0.2685],
        [0.7654, 0.3730, 0.1325, 0.6538, 0.9916, 0.4799]])

#### Random samples from standard normal distribution :

In [35]:
torch.randn(5,6)

tensor([[-8.1440e-04,  1.4749e-01, -1.4111e-01, -3.2290e-01, -4.9863e+00,
         -9.0856e-01],
        [ 6.9325e-01,  1.4722e+00,  2.4181e-01, -8.7337e-01, -1.3918e+00,
         -1.1394e+00],
        [-1.4920e+00, -1.1649e+00, -8.1038e-01, -2.3070e-01, -1.5525e+00,
         -3.4707e-01],
        [-3.3485e-01, -1.2151e+00, -1.0923e+00, -3.7251e-01,  2.0500e-01,
          8.2873e-01],
        [-2.3861e+00,  8.3957e-02,  1.2036e-01, -5.7526e-01, -1.7348e+00,
          1.3557e+00]])

In [36]:
torch.randint(low=0, high=10, size=(6,6))
# High is exlusive

tensor([[3, 8, 4, 5, 3, 6],
        [5, 9, 8, 8, 7, 1],
        [6, 7, 3, 4, 5, 6],
        [0, 0, 1, 7, 6, 2],
        [9, 9, 4, 0, 1, 2],
        [4, 4, 6, 8, 9, 9]])

In [37]:
torch.rand_like(ts3)

tensor([0.0985, 0.5365, 0.2875, 0.5172, 0.0940, 0.3681, 0.6268, 0.8727])

In [38]:
torch.randn_like(ts3)

tensor([ 1.2247, -1.0732,  1.6091,  0.9392, -2.6469, -0.4293,  0.7544,  0.2217])

#### Set seed for random values : 

In [40]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [41]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [42]:
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])