In [1]:
import torch
import numpy as np

In [3]:
ts = torch.arange(0,9).reshape(3,3)
ts[:2][:1]

tensor([[0, 1, 2]])

In [4]:
type(ts[2][2])

torch.Tensor

In [5]:
ts

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [9]:
ts[:,2:]

tensor([[2],
        [5],
        [8]])

In [10]:
ts_2 = torch.arange(0, 10)
ts_2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
ts_2.view(2, -1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
a = torch.tensor([1., 2., 3., 4.])
b = torch.tensor([5., 6., 7., 8.])
c = a + b
d = torch.add(a, b)
print(c)
print(d)

tensor([ 6.,  8., 10., 12.])
tensor([ 6.,  8., 10., 12.])


In [14]:
a.mul(b)

tensor([ 5., 12., 21., 32.])

In [15]:
a

tensor([1., 2., 3., 4.])

In [16]:
a.mul_(b)
a

tensor([ 5., 12., 21., 32.])

#### Dot product :

In [17]:
a.dot(b)

tensor(500.)

#### Matrix Multiplication :

In [18]:
a = torch.tensor([[1], [2]])
a.shape

torch.Size([2, 1])

In [19]:
b = torch.tensor([[2, 1]])
b.shape

torch.Size([1, 2])

In [20]:
a @ b

tensor([[2, 1],
        [4, 2]])

In [21]:
torch.mm(a, b)

tensor([[2, 1],
        [4, 2]])

#### L2 (Euclidean) Norm :

In [22]:
a.numel()

2

In [24]:
a = a.type(torch.float64)
a.norm()

tensor(2.2361, dtype=torch.float64)

In [25]:
a

tensor([[1.],
        [2.]], dtype=torch.float64)